name: Build and Trigger Kubeflow Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'image/Dockerfile'

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./image
          push: true
          tags: |
            lukoprych/yolov8-pipeline-base:${{ github.sha }}
            lukoprych/yolov8-pipeline-base:latest
      
      - name: Trigger Kubeflow Pipeline
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}" \
            -d '{
              "run_name": "webhook-run",
              "experiment_id": "${{ secrets.EXPERIMENT_ID }}",
              "pipeline_id": "${{ secrets.PIPELINE_ID }}",
              "version_id": "${{ secrets.VERSION_ID }}",
              "namespace": "kubeflow-user-example-com"
            }'
